name = "AbbreviatedTypes"
uuid = "1766def0-c946-4dda-a59e-d0d07f8410f7"
authors = ["Wonseok Shin <wsshin97@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
