name = "AbbreviatedTypes"
uuid = "1766def0-c946-4dda-a59e-d0d07f8410f7"
authors = ["Wonseok Shin <wsshin97@gmail.com> and contributors"]
version = "0.3.2"

[deps]
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
Reexport = "1.0.0 - 1"
StaticArrays = "1.5.0 - 1"
julia = "1.7 - 1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
